# Sampling Plan

_Describe how you plan to collect samples, as well as the number of samples you
plan to collect and your rationale for this decision. Please keep in mind that
the data described in this section should be the actual data used for analysis,
so if you are using a subset of a larger dataset, please describe the subset
that will actually be used in your study._

## Details of Larger Project

Is your preregistration part of a larger project?

- No
- Yes

  > If yes, provide a brief description of the larger study or, if applicable,
  > link to the OSF project page, a related preregistration, a poster, etc. You
  > may also include a figure detailing the protocol of the project. Note, this
  > is meant to provide context for the larger scope of the project.

## Existing data

Preregistration is designed to emphasize the distinction between confirmatory
tests, specified prior to seeing the data, and exploratory analyses conducted
without specific hypothesis or after observing the data. Therefore, creating a
research plan in which existing data will be used presents unique challenges.
For research that uses existing datasets (e.g. Human Connectome Project, UK
biobank, etc.), we also refer to the OSF preregistration template for secondary
data analysis, which was designed specifically for this type of analytical
research [https://osf.io/x4gzt/](https://osf.io/x4gzt/). Please select the
description that best describes your situation:

- Registration prior to creation of data
- Registration prior to accessing the data
- Registration prior to any human observation of the data
- Registration prior to analysis of the data
- Registration following analysis of the data

### Explanation of Existing Data

If you indicate that you will be using some data that already exists in this
study, please describe your prior knowledge of any patterns or summary
statistics in the data. This may include an explanation of how access to the
data has been limited, who has observed the data, and if/what is already known
about the sample you investigate (e.g., links to prior papers, osf project page,
prior posters or talks, or descriptions). The purpose of this question is to
assure that the line between confirmatory and exploratory analysis is clear.

## Data collection

Is this preregistration done before data collection?

- No

  > There is no need to describe the data collection in complete detail in your
  > preregistration. Nonetheless, it is strongly recommended to include
  > information on your sample (see checklist below), behavioral and fMRI data
  > acquisition (**Appendix 2**) in a short paragraph as it would appear in the
  > Methods section of a publication. Especially mention details important for
  > your choices in **Variables** and **Analysis Plan** (e.g. temporal/spatial
  > resolution of fMRI which may motivate certain preprocessing or analysis
  > procedures).

- Yes

  > Describe all steps of data collection including your sample description (see
  > checklist below). Make sure to detail procedures of all relevant behavioral
  > and fMRI data acquisition steps. Other measurements relevant to address your
  > hypotheses or that are included for different purposes (e.g., characterizing
  > groups, sensitivity analysis, exploratory analysis) may also be detailed
  > here. For the task-based fMRI measurements you can use the table in
  > **Appendix 2** as a checklist of topics to cover in this description.

_Note: There may be some overlap between this and other sections. Again, that is
OK, as long as sufficient detail is given in one of the areas to provide all of
the requested information._

### Sample description

|      |                                                                          |
| ---- | ------------------------------------------------------------------------ |
| \_\_ | Population                                                               |
| \_\_ | Recruitment efforts                                                      |
| \_\_ | Inclusion criteria                                                       |
| \_\_ | Exclusion criteria                                                       |
| \_\_ | Reimbursement for participation                                          |
| \_\_ | Information on ethics approval and informed consent                      |
| \_\_ | Number of participants tested and analyzed                               |
| \_\_ | Age                                                                      |
| \_\_ | Sex / Gender                                                             |
| \_\_ | Handedness                                                               |
| \_\_ | or NA Clinical criteria                                                  |
| \_\_ | or NA Matching strategy                                                  |
| \_\_ | or NA Other relevant participant or group characteristics for your study |
| \_\_ | Study timeline including all measures                                    |

### Other Measures

Please specify all additional measures you plan to investigate, for example:

- **Experimental tasks outside the scanner:**

  > For each additional behavioral task, give a short description and specify
  > the design and task. You may use the table for the design of scanner tasks
  > in the section **Design Plan** as a checklist.

- **Questionnaires and standardized assessments:**

  > For each questionnaire and standardized assessment, mention the name and
  > version.

- **Additional neuroimaging measures:**

  > Give a description and brief purpose statement of any other imaging
  > modalities that will be included in your study (e.g., EEG, Neuromodulation
  > (TMS, tDCS, ...)).

- **Physiological recordings:**
  > Give a description and brief purpose statement of any physiological data
  > that will be collected from the participants before/during/after fMRI (e.g.
  > eye-tracking, pulse, electrocardiography, plethysmography (pulse oximetry),
  > respiration, blood pressure, blood samples, skin conductance (SCR),
  > electromyography, etc.). For each measure, mention the device.

_Note that parts of this section may be covered in the Design Plan section
instead._

## Sample Size

State your target sample size and, if applicable, your stopping rule. Justify
your choices.

Justification of sample size or stopping rule:

|           |                                                                                                                                                                                                                                                                                                                               |
| --------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| \_\_or NA | Power Analysis for fMRI or behavioral analysis. Please provide all details on your calculation. (strongly recommended, no standard procedures for fMRI power analysis but see https://brainpower.readthedocs.io/en/latest/index.html{.underline}(https://brainpower.readthedocs.io/en/latest/index.html) for available tools) |
| \_\_or NA | Time constraints (e.g., will recruit for one year or until X date)                                                                                                                                                                                                                                                            |
| \_\_or NA | Money constraints (e.g., monetary support will support up to Xsubjects)                                                                                                                                                                                                                                                       |
| \_\_or NA | Personnel constraints (e.g., will recruit for time period in which personnel support is available)                                                                                                                                                                                                                            |
| \_\_      | ** Other:**                                                                                                                                                                                                                                                                                                                   |

If possible, include contingencies for if your target sample size is not met.
E.g., how will hypotheses be adopted to better powered question?
