# Variables

_In this section you can describe all variables (both manipulated and measured
variables) that will later be used in your analysis plan. In your analysis plan,
you will have the opportunity to describe how each variable will be used. If you
have variables which you are measuring for exploratory analyses, you are not
required to list them, though you are permitted to do so._

## Manipulated variables

Describe all variables you plan to manipulate and the levels or treatment arms
of each variable. This is not applicable to an observational study.

## Measured variables*

### Behavioral data

Describe each variable that you will measure and indicate the corresponding
confirmatory hypothesis. You can use the checklist below.

| **Measured variables** |                                                                                                                                                                                                                                                                                                                                                                                                                              |
| ---------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| \_\_                   | **Outcome** measures/dependent variables (specify whether confirmatory or exploratory outcome, how variable was measured, scale/range of measure, which subscale/component of measure you will use).                                                                                                                                                                                                                         |
| \_\_                   | **Predictor** measures/independent variables (specific measure, scale/range of measure, which subscale/component of measure you will use).                                                                                                                                                                                                                                                                                   |
| \_\_ or NA             | **Covariate** measures (specific measure, scale/range of measure, which subscale/component of measure you will use).                                                                                                                                                                                                                                                                                                         |
| **Quality control**    |                                                                                                                                                                                                                                                                                                                                                                                                                              |
| \_\_                   | Any outcome-neutral criteria that must be met for successful testing of the stated hypotheses. Such quality checks might include the absence of floor or ceiling effects in data distributions, positive controls, or other quality checks that are orthogonal to the experimental hypotheses.                                                                                                                               |
| \_\_ or NA             | How will you determine which subjects, data points or measures (if any) to **exclude** from your analyses? If possible, specify objective exclusion criteria (due to technical errors, slow reactions, instructions not understood, accuracy below a certain threshold, or for any other reasons).                                                                                                                           |
| \_\_ or NA             | How will you deal with incomplete or missing data (e.g., missing timepoints or missing/incomplete data within or between runs; what percent missing will be included)? Under what conditions would data be replaced and how?                                                                                                                                                                                                 |
| \_\_ or NA             | If possible, define contingency plans how to proceed in such cases, (e.g., plans if x% of behavioral data is missing; if the X questionnaire is missing for more than 10% of participants we will not use it or if X does not show variability in response (either ceiling or floor effects) in which we cannot look at behavioral pattern of interest, we will not use that questionnaire and use Y questionnaire instead). |
| **Transformations**    |                                                                                                                                                                                                                                                                                                                                                                                                                              |
| \_\_ or NA             | If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process.                                                                                                                                                                                                                                                                          |
|                        | Include contingency plans for transformation: (e.g., transformations that will occur if data are skewed or for model convergence/multicollinearity)                                                                                                                                                                                                                                                                          |
| **Code**               |                                                                                                                                                                                                                                                                                                                                                                                                                              |
| \_\_ or NA             | Link to shared code for scoring behavioral data.                                                                                                                                                                                                                                                                                                                                                                             |

### fMRI data

Describe what variable will be measured (e.g., BOLD response) and detail all
preprocessing steps. You can fill in the table or write paragraph below as you
would for paper and use the table as checklist of topics covered.

For each piece of software used, give the version number. Also indicate which
platform you ran the software on.

| **Quality control**                                                                                        |                                                                                                                                                                                                                                                                                        | **software, version** |
| ---------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------- |
| \_\_ or NA                                                                                                 | incidental findings (Protocol for review of any incidental findings, and how they are handled in particular with respect to possible exclusion of a subject's data.)                                                                                                                   |                       |
| \_\_ or NA                                                                                                 | motion monitoring (For functional acquisitions, any visual or qualitative checks for severe motion; likewise, for structural images, checks on motion or general image quality.) Including prospective quantitative motion monitoring and/or correction?{dir="ltr "}                   |                       |
| \_\_ or NA                                                                                                 | How will you determine which data points or samples (if any) to exclude from your analyses? How will outliers be defined and handled? If possible, specify objective exclusion criteria, e.g.                                                                                          |                       |
|                                                                                                            | - a participant has X percentage of volumes with motion or exceeds pre-defined motion threshold?                                                                                                                                                                                       |                       |
|                                                                                                            | - general artifacts qualitatively or quantitatively defined (multi band stripes, respiration-related ... )                                                                                                                                                                             |                       |
|                                                                                                            | - registration fails because of atrophy, brain lesion ...                                                                                                                                                                                                                              |                       |
| \_\_ or NA                                                                                                 | How will you deal with incomplete or missing data (e.g., missing timepoints or missing/incomplete data within or between runs; what percent missing will be included)? Under what conditions would data be replaced?                                                                   |                       |
| \_\_ or NA                                                                                                 | Other quantitative quality control metrics (signal-to-noise ratio, contrast-to-noise ratio, motion parameters, outliers, etc)? How will these be assessed (e.g. which software, version, etc)? Will any of these metrics factor into the decision to exclude subjects? If so, how?     |                       |
| **Anatomical preprocessing** (e.g. which steps are taken before coregistration of anatomical & functional) |                                                                                                                                                                                                                                                                                        |                       |
| \_\_ or NA                                                                                                 | Intensity non-uniformity correction                                                                                                                                                                                                                                                    |                       |
| \_\_ or NA                                                                                                 | brain extraction                                                                                                                                                                                                                                                                       |                       |
| \_\_ or NA                                                                                                 | tissue segmentation                                                                                                                                                                                                                                                                    |                       |
| **Functional preprocessing**                                                                               |                                                                                                                                                                                                                                                                                        |                       |
| \_\_ or NA                                                                                                 | Remove first volumes to reach steady-state (during acquisition or preprocessing)? How many volumes were discarded?                                                                                                                                                                     |                       |
| \_\_ or NA                                                                                                 | **Distortion correction** (fieldmap, ap-pa acquisitions)                                                                                                                                                                                                                               |                       |
| \_\_ or NA                                                                                                 | **Intensity normalization**                                                                                                                                                                                                                                                            |                       |
| \_\_ or NA                                                                                                 | **Slice timing correction** (specify reference slice, e.g.,first slice, and interpolation, e.g., Fourier phase shift interpolation)                                                                                                                                                    |                       |
| \_\_ or NA                                                                                                 | **Primary motion correction (realignment)** (reference scan for realignment, image similarity metric, type of interpolation used, degrees-of-freedom and optimization method)                                                                                                          |                       |
| \_\_ or NA                                                                                                 | **Intrasubject registration** (e.g. anatomical to functional)                                                                                                                                                                                                                          |                       |
| \_\_ or NA                                                                                                 | Directionality (e.g. anatomical to functional, functional session 1 to functional session 2, etc)                                                                                                                                                                                      |                       |
| \_\_ or NA                                                                                                 | Transformation model (linear or nonlinear)                                                                                                                                                                                                                                             |                       |
| \_\_ or NA                                                                                                 | Degrees of freedom                                                                                                                                                                                                                                                                     |                       |
| \_\_ or NA                                                                                                 | Interpolation method                                                                                                                                                                                                                                                                   |                       |
| \_\_ or NA                                                                                                 | Image similarity metric                                                                                                                                                                                                                                                                |                       |
| \_\_ or NA                                                                                                 | **Intersubject registration** (e.g. anatomical/functional to template) Brain image template space, name, modality and resolution (e.g., MNI Avg152, T1 2 × 2 × 2 mm; customized sample template)                                                                                       |                       |
| \_\_ or NA                                                                                                 | Directionality (e.g. anatomical to functional, functional session 1 to functional session 2, etc)                                                                                                                                                                                      |                       |
| \_\_ or NA                                                                                                 | Transformation model (linear or nonlinear)                                                                                                                                                                                                                                             |                       |
| \_\_ or NA                                                                                                 | Degrees of freedom                                                                                                                                                                                                                                                                     |                       |
| \_\_ or NA                                                                                                 | Interpolation method                                                                                                                                                                                                                                                                   |                       |
| \_\_ or NA                                                                                                 | Image similarity metric                                                                                                                                                                                                                                                                |                       |
| \_\_ or NA                                                                                                 | **Smoothing** Size and type of smoothing kernel (provide justification for size; e.g., for a group study, "12 mm FHWM Gaussian smoothing applied to ameliorate differences in intersubject localization"; for single subject fMRI "6 mm FWHM Gaussian smoothing used to reduce noise") |                       |
| \_\_ or NA                                                                                                 | **Temporal filtering** (type of filter, frequency band)                                                                                                                                                                                                                                |                       |
| **Flowchart**                                                                                              |                                                                                                                                                                                                                                                                                        |                       |
| \_\_ or NA                                                                                                 | A flowchart can be attached that depicts the order of the preprocessing steps for each acquisition type (anatomical and functional).                                                                                                                                                   |                       |
| **Code**                                                                                                   |                                                                                                                                                                                                                                                                                        |                       |
| \_\_ or NA                                                                                                 | Link to shared code for preprocessing data                                                                                                                                                                                                                                             |                       |
