# Appendix 3: Additional fMRI analyses

## Functional connectivity

|                                                                |                                                                                                                                                                                                                                                        |
| -------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| **Confound adjustment & filtering Report**                     |                                                                                                                                                                                                                                                        |
| \_\_or NA                                                      | Method for detecting movement artifacts, movement-related variation, and remediation (e.g. 'scrubbing', 'despiking', etc)                                                                                                                              |
| \_\_or NA                                                      | Use of global signal regression, exact type of global signal used and how it was computed                                                                                                                                                              |
| \_\_or NA                                                      | Whether a high or lowpass temporal filtering is applied to data, and at which point in the analysis pipeline. Note, any temporal regression model using filtered data should have its regressors likewise filtered                                     |
| **Multivariate method: Independent Component Analysis Report** |                                                                                                                                                                                                                                                        |
| \_\_or NA                                                      | Algorithm to estimate components                                                                                                                                                                                                                       |
| \_\_or NA                                                      | Number of components (if fixed), or algorithm for estimating number of components                                                                                                                                                                      |
| \_\_or NA                                                      | If used, method to synthesize multiple runs                                                                                                                                                                                                            |
| \_\_or NA                                                      | Sorting method of IC's, if any                                                                                                                                                                                                                         |
| \_\_or NA                                                      | Detailed description of how components were chosen for further analysis                                                                                                                                                                                |
| \_\_or NA                                                      | Dependent variable definition                                                                                                                                                                                                                          |
| **For seed-based analyses report**                             |                                                                                                                                                                                                                                                        |
| \_\_or NA                                                      | Definition of the seed region(s)                                                                                                                                                                                                                       |
| \_\_or NA                                                      | Rationale for choosing these regions                                                                                                                                                                                                                   |
| **For region-based analyses report**                           |                                                                                                                                                                                                                                                        |
| \_\_or NA                                                      | Number of ROIs                                                                                                                                                                                                                                         |
| \_\_or NA                                                      | How the ROI's are defined (e.g. citable anatomical atlas; auxiliary fMRI experiments); note if ROIs overlap                                                                                                                                            |
| \_\_or NA                                                      | Assignment of signals to regions (i.e. how a time series is obtained from each region, e.g. averaging or first singular vector)                                                                                                                        |
| \_\_or NA                                                      | Note if considering only bilateral (L+R) merged regions                                                                                                                                                                                                |
| \_\_or NA                                                      | Note if considering only interhemispheric homotopic connectivity                                                                                                                                                                                       |
| **Functional connectivity measure/model Report**               |                                                                                                                                                                                                                                                        |
| \_\_or NA                                                      | Measure of dependence used, e.g. Pearson's (full) correlation, partial correlation, mutual information, etc; also specify:                                                                                                                             |
| \_\_or NA                                                      | Use of Fisher's Z-transform (Yes/No) and, if standardised, effective N is used to compute standard error (to account for any filtering operations on the data)                                                                                         |
| \_\_or NA                                                      | Estimator used for partial correlation                                                                                                                                                                                                                 |
| \_\_or NA                                                      | Estimator used for mutual information                                                                                                                                                                                                                  |
| \_\_or NA                                                      | Regression model used to remove confounding effects (Pearson or partial correlation)                                                                                                                                                                   |
| **Effectivity connectivity Report**                            |                                                                                                                                                                                                                                                        |
| \_\_or NA                                                      | Model                                                                                                                                                                                                                                                  |
| \_\_or NA                                                      | Algorithm used to fit model                                                                                                                                                                                                                            |
| \_\_or NA                                                      | If per subject model, method used to generalize inferences to population. Itemize models considered, and method used for model comparison                                                                                                              |
| **Graph analysis**                                             |                                                                                                                                                                                                                                                        |
| \_\_or NA                                                      | Report the 'dependent variable' and 'functional connectivity measure' used (see above). Specify either:                                                                                                                                                |
| \_\_or NA                                                      | - Weighted graph analysis or                                                                                                                                                                                                                           |
| \_\_or NA                                                      | - Binarized graph analysis is used, clarifying the method used for thresholding (e.g. a 10% density threshold, or a statistically defined threshold); consider the sensitivity of your findings to the particular choice of threshold used             |
| \_\_or NA                                                      | Itemise the graph summaries used (e.g. clustering coefficient, efficiency, etc), whether these are global or per¬node/per¬edge summaries. In particular with fMRI or EEG, clarify if measures applied to individual subject networks or group networks |

## Decoding analysis

|           |                                                                      |
| --------- | -------------------------------------------------------------------- |
| \_\_or NA | Algorithm choice(s)                                                  |
| \_\_or NA | Hyperparameter optimization                                          |
| \_\_or NA | Cross-validation regimen including whether stratification is applied |
| \_\_or NA | Hold-out samples                                                     |
